#Cài đặt thư viện

In [1]:
pip install vnstock

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vnstock
  Downloading vnstock-0.1.0-py3-none-any.whl (14 kB)
Installing collected packages: vnstock
Successfully installed vnstock-0.1.0

In [2]:
from vnstock import *

#Demo truy xuất dữ liệu

##Liệt kê danh sách các mã cổ phiếu trên thị trường

In [3]:
listing_companies()

,ticker,group_code,company_name,company_short_name
0,HSV,UpcomIndex,Công ty Cổ phần Gang Thép Hà Nội,Gang Thép Hà Nội
1,SCV,UpcomIndex,Công ty Cổ phần Muối Việt Nam,"Visalco.,JSC"
2,LYF,UpcomIndex,Công ty Cổ phần Lương Thực Lương Yên,Công ty Lương Thực Lương Yên
3,CST,UpcomIndex,Công ty Cổ phần Than Cao Sơn - TKV,Than Cao Sơn - TKV
4,BVL,UpcomIndex,Công ty Cổ phần BV Land,BV Land
...,...,...,...,...
1620,XMP,UpcomIndex,Công ty Cổ phần Thủy điện Xuân Minh,Thủy điện Xuân Minh
1621,YBC,UpcomIndex,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,Xi măng và Khoáng sản Yên Bái
1622,YBM,VNINDEX,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,Khoáng sản CN Yên Bái
1623,YEG,VNINDEX,Công ty Cổ phần Tập đoàn Yeah1,Tập đoàn Yeah1
1624,YTC,UpcomIndex,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,XNK Y tế TP.HCM

##Tóm tắt thông tin cơ bản của một mã cổ phiếu bất kì

In [4]:
#Tóm tắt thông tin mã cổ phiếu TCB
ticker_overview('TCB')

,exchange,shortName,industryID,industryIDv2,industry,industryEn,establishedYear,noEmployees,noShareholders,foreignPercent,website,stockRating,deltaInWeek,deltaInMonth,deltaInYear,outstandingShare,issueShare,companyType,ticker
0,HOSE,Techcombank,289,8355,Ngân hàng,Banks,1993,9757,1901,0.225,http://www.techcombank.com.vn,2.8,0.009,-0.052,-0.187,3517.2,3510.9,NH,TCB

##Tra cứu dữ liệu lịch sử giá của 1 mã cổ phiếu bất kì

In [5]:
df = stock_historical_data(symbol='TCB', start_date='2021-01-01', end_date='2022-09-09')
df

        Open     High      Low    Close    Volume TradingDate
0    32000.0  33400.0  31900.0  33000.0  18607800  2021-01-04
1    32750.0  33350.0  32550.0  33050.0  14280100  2021-01-05
2    33200.0  34100.0  32950.0  33200.0  20222300  2021-01-06
3    33700.0  34600.0  33400.0  34600.0  16387200  2021-01-07
4    35000.0  36250.0  34900.0  35700.0  16947900  2021-01-08
..       ...      ...      ...      ...       ...         ...
414  38850.0  38900.0  38550.0  38600.0   2788600  2022-09-05
415  38550.0  39000.0  38550.0  38650.0   2340700  2022-09-06
416  38650.0  38700.0  37550.0  37550.0   4269000  2022-09-07
417  37750.0  37900.0  37350.0  37400.0   2473200  2022-09-08
418  37700.0  37700.0  37000.0  37650.0   2951100  2022-09-09

[419 rows x 6 columns]

##So sánh thông tin giao dịch của 1 danh sách các mã cổ phiếu cần tra cứu

In [7]:
price_board('TCB,SSI,VND')

,Mã CP,Giá Khớp Lệnh,KLBD/TB5D,T.độ GD,KLGD ròng(CM),%KLGD ròng (CM),RSI,MACD Volume,MACD Signal,Tín hiệu KT,...,Khối lượng Dư mua,Khối lượng Dư bán,Khớp nhiều nhất,seq,vnid3d,vnid1m,vnid3m,vnid1y,vnipe,vnipb
0,TCB,33000.0,0.89,1.97,-66300,-19.2,18.3791,-0.33,Neutral,Neutral,...,190300,4800,33300,1664438340,-2.6,-10.8,-4.9,-13.7,12.6292,1.81434
1,SSI,19300.0,0.75,1.59,-472800,-29.8,30.7557,-0.20,Neutral,Neutral,...,110300,505100,19300,1664438340,-2.6,-10.8,-4.9,-13.7,12.6292,1.81434
2,VND,17400.0,0.64,1.49,75000,4.5,32.3743,-0.20,Neutral,Neutral,...,173900,477900,17400,1664438340,-2.6,-10.8,-4.9,-13.7,12.6292,1.81434

##Dữ liệu intraday thể hiện thông tin giao dịch theo thời gian trong ngày

In [9]:
stock_intraday_data(symbol='GMD', page_num=0, page_size=5000)

        price  volume   cp  rcp   a   ba   sa     hl  pcp      time
0     48000.0   71100  0.0  0.0      0.0  0.0   True  0.0  14:45:03
1     47800.0     300  0.0  0.0  BU  0.0  0.0  False  0.0  14:29:29
2     47700.0     300  0.0  0.0  BU  0.0  0.0  False  0.0  14:29:21
3     47650.0     100  0.0  0.0  BU  0.0  0.0  False  0.0  14:29:02
4     47700.0     400  0.0  0.0  BU  0.0  0.0  False  0.0  14:29:02
...       ...     ...  ...  ...  ..  ...  ...    ...  ...       ...
1381  47200.0    1900  0.0  0.0  SD  0.0  0.0  False  0.0  09:17:52
1382  47200.0     100  0.0  0.0  SD  0.0  0.0  False  0.0  09:17:04
1383  47150.0     500  0.0  0.0  SD  0.0  0.0  False  0.0  09:15:09
1384  47100.0     500  0.0  0.0  SD  0.0  0.0  False  0.0  09:15:09
1385  47150.0   16400  0.0  0.0      0.0  0.0   True  0.0  09:15:03

[1386 rows x 10 columns]

#Xuất dữ liệu

In [10]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [11]:
df = stock_historical_data(symbol='TCB', start_date='2021-01-01', end_date='2022-09-09')
df.head()

      Open     High      Low    Close    Volume TradingDate
0  32000.0  33400.0  31900.0  33000.0  18607800  2021-01-04
1  32750.0  33350.0  32550.0  33050.0  14280100  2021-01-05
2  33200.0  34100.0  32950.0  33200.0  20222300  2021-01-06
3  33700.0  34600.0  33400.0  34600.0  16387200  2021-01-07
4  35000.0  36250.0  34900.0  35700.0  16947900  2021-01-08

In [14]:
#Lưu file dưới dạng file .csv
df.to_csv('/content/drive/MyDrive/Data_of_stock_ticker_TCB.csv', index=False)

In [12]:
#Lưu file dưới dạng file .xlsx
#df.to_excel('/content/drive/MyDrive/Data_of_stock_ticker_TCB.xlsx', index=False)